use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

/// Project type detected from the filesystem.
#[derive(Debug, Clone, PartialEq)]
pub enum ProjectType {
    Rust,
    Python,
    JavaScript,
    TypeScript,
    Go,
    Unknown,
}

impl std::fmt::Display for ProjectType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ProjectType::Rust => write!(f, "Rust"),
            ProjectType::Python => write!(f, "Python"),
            ProjectType::JavaScript => write!(f, "JavaScript"),
            ProjectType::TypeScript => write!(f, "TypeScript"),
            ProjectType::Go => write!(f, "Go"),
            ProjectType::Unknown => write!(f, "Unknown"),
        }
    }
}

/// Detect project type from the current directory.
pub fn detect_project_type(dir: &Path) -> ProjectType {
    if dir.join("Cargo.toml").exists() {
        ProjectType::Rust
    } else if dir.join("tsconfig.json").exists() {
        ProjectType::TypeScript
    } else if dir.join("package.json").exists() {
        ProjectType::JavaScript
    } else if dir.join("go.mod").exists() {
        ProjectType::Go
    } else if dir.join("pyproject.toml").exists()
        || dir.join("setup.py").exists()
        || dir.join("requirements.txt").exists()
    {
        ProjectType::Python
    } else {
        ProjectType::Unknown
    }
}

/// Extract key dependencies from project manifest files.
pub fn detect_dependencies(dir: &Path, project_type: &ProjectType) -> Vec<String> {
    match project_type {
        ProjectType::Rust => detect_rust_deps(dir),
        ProjectType::Python => detect_python_deps(dir),
        ProjectType::JavaScript | ProjectType::TypeScript => detect_js_deps(dir),
        ProjectType::Go => detect_go_deps(dir),
        ProjectType::Unknown => vec![],
    }
}

fn detect_rust_deps(dir: &Path) -> Vec<String> {
    let cargo_toml = dir.join("Cargo.toml");
    if !cargo_toml.exists() {
        return vec![];
    }
    let content = std::fs::read_to_string(&cargo_toml).unwrap_or_default();
    let mut deps = vec![];
    let mut in_deps = false;
    for line in content.lines() {
        if line.starts_with("[dependencies]") || line.starts_with("[dev-dependencies]") {
            in_deps = true;
            continue;
        }
        if line.starts_with('[') {
            in_deps = false;
            continue;
        }
        if in_deps {
            if let Some(name) = line.split('=').next() {
                let name = name.trim();
                if !name.is_empty() && !name.starts_with('#') {
                    deps.push(name.to_string());
                }
            }
        }
    }
    deps
}

fn detect_python_deps(dir: &Path) -> Vec<String> {
    let req = dir.join("requirements.txt");
    if req.exists() {
        return std::fs::read_to_string(&req)
            .unwrap_or_default()
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .map(|l| l.split(&['=', '>', '<', '~', '!', '['][..]).next().unwrap_or(l).trim().to_string())
            .filter(|s| !s.is_empty())
            .collect();
    }
    vec![]
}

fn detect_js_deps(dir: &Path) -> Vec<String> {
    let pkg = dir.join("package.json");
    if !pkg.exists() {
        return vec![];
    }
    let content = std::fs::read_to_string(&pkg).unwrap_or_default();
    let parsed: serde_json::Value = serde_json::from_str(&content).unwrap_or_default();
    let mut deps = vec![];
    for section in &["dependencies", "devDependencies"] {
        if let Some(obj) = parsed.get(section).and_then(|v| v.as_object()) {
            for key in obj.keys() {
                deps.push(key.clone());
            }
        }
    }
    deps
}

fn detect_go_deps(dir: &Path) -> Vec<String> {
    let gomod = dir.join("go.mod");
    if !gomod.exists() {
        return vec![];
    }
    let content = std::fs::read_to_string(&gomod).unwrap_or_default();
    content
        .lines()
        .filter(|l| l.starts_with('\t') || l.starts_with("require "))
        .map(|l| l.trim().split_whitespace().next().unwrap_or("").to_string())
        .filter(|s| !s.is_empty() && s != "require" && s != "(")
        .collect()
}

/// Generate rigor.yaml content for the detected project.
pub fn generate_rigor_yaml(project_type: &ProjectType, deps: &[String]) -> String {
    use crate::defaults;

    let mut yaml = String::new();
    yaml.push_str("# Rigor constraint configuration\n");
    yaml.push_str(&format!("# Project type: {}\n", project_type));
    yaml.push_str("# Generated by: rigor init\n");
    yaml.push_str("#\n");
    yaml.push_str("# Three tiers of constraints:\n");
    yaml.push_str("#   1. Language defaults — truths about the language itself\n");
    yaml.push_str("#   2. Dependency constraints — truths about specific libraries\n");
    yaml.push_str("#   3. Project constraints — run /rigor:map to generate these\n");
    yaml.push_str("\nconstraints:\n");
    yaml.push_str("  beliefs:\n");

    // ── Tier 1: Language defaults ──
    match project_type {
        ProjectType::Rust => {
            yaml.push_str(defaults::rust::rust_language_constraints());
        }
        ProjectType::Go => {
            yaml.push_str(defaults::go::go_language_constraints());
        }
        _ => {}
    }

    // ── Tier 2: Dependency constraints ──
    let mut dep_count = 0;
    for dep in deps {
        if let Some(constraint_yaml) = defaults::deps::constraints_for_crate(dep) {
            yaml.push_str(constraint_yaml);
            dep_count += 1;
        }
    }

    // ── Tier 3: Project constraints placeholder ──
    yaml.push_str(r#"
    # ── Project Constraints ─────────────────────────────────────────
    # Run /rigor:map in Claude Code to generate code-anchored constraints
    # specific to YOUR project. These are the most valuable constraints —
    # they protect facts that only exist in your codebase.

"#);

    // ── Relations ──
    // Language constraints support each other
    yaml.push_str("  justifications: []\n");
    yaml.push_str("  defeaters: []\n\n");
    yaml.push_str("relations: []\n");

    let lang_count = match project_type {
        ProjectType::Rust => 5,
        ProjectType::Go => 5,
        _ => 0,
    };

    eprintln!("rigor: {} language defaults, {} dependency constraints", lang_count, dep_count);
    eprintln!("rigor: run /rigor:map to add project-specific constraints");

    yaml
}

/// Gather project context for AI analysis.
fn gather_project_context(dir: &Path, project_type: &ProjectType, deps: &[String]) -> String {
    let mut ctx = String::new();
    ctx.push_str(&format!("Project type: {}\n", project_type));
    ctx.push_str(&format!("Directory: {}\n", dir.display()));

    if !deps.is_empty() {
        ctx.push_str(&format!("Dependencies: {}\n", deps.join(", ")));
    }

    // Read manifest
    let manifests = ["Cargo.toml", "package.json", "go.mod", "pyproject.toml"];
    for m in manifests {
        let p = dir.join(m);
        if p.exists() {
            if let Ok(content) = std::fs::read_to_string(&p) {
                ctx.push_str(&format!("\n--- {} ---\n", m));
                // Limit to first 3000 chars
                ctx.push_str(&content.chars().take(3000).collect::<String>());
                ctx.push('\n');
            }
        }
    }

    // Read README or CLAUDE.md
    for readme in ["CLAUDE.md", "README.md", "readme.md"] {
        let p = dir.join(readme);
        if p.exists() {
            if let Ok(content) = std::fs::read_to_string(&p) {
                ctx.push_str(&format!("\n--- {} ---\n", readme));
                ctx.push_str(&content.chars().take(3000).collect::<String>());
                ctx.push('\n');
                break;
            }
        }
    }

    // Read entry point files (first 100 lines)
    let entry_points: Vec<&str> = match project_type {
        ProjectType::Rust => vec!["src/main.rs", "src/lib.rs"],
        ProjectType::Python => vec!["main.py", "app.py", "src/main.py"],
        ProjectType::JavaScript | ProjectType::TypeScript => {
            vec!["src/index.ts", "src/index.js", "index.ts", "index.js"]
        }
        ProjectType::Go => vec!["main.go", "cmd/main.go"],
        ProjectType::Unknown => vec![],
    };

    for ep in entry_points {
        let p = dir.join(ep);
        if p.exists() {
            if let Ok(content) = std::fs::read_to_string(&p) {
                let lines: Vec<&str> = content.lines().take(100).collect();
                ctx.push_str(&format!("\n--- {} (first 100 lines) ---\n", ep));
                ctx.push_str(&lines.join("\n"));
                ctx.push('\n');
            }
        }
    }

    // Directory tree (depth 2)
    if let Ok(output) = std::process::Command::new("find")
        .args([dir.to_str().unwrap_or("."), "-maxdepth", "2", "-type", "f"])
        .arg("-not").arg("-path").arg("*/target/*")
        .arg("-not").arg("-path").arg("*/node_modules/*")
        .arg("-not").arg("-path").arg("*/.git/*")
        .output()
    {
        let tree = String::from_utf8_lossy(&output.stdout);
        let limited: String = tree.lines().take(50).collect::<Vec<&str>>().join("\n");
        ctx.push_str("\n--- File tree (depth 2) ---\n");
        ctx.push_str(&limited);
        ctx.push('\n');
    }

    ctx
}

/// Build the AI prompt for constraint generation.
fn build_ai_prompt(context: &str) -> String {
    format!(r#"You are analyzing a software project to generate epistemic constraints for "rigor", a tool that enforces claim quality in AI-assisted development.

Rigor validates claims that AI assistants make about code. Each constraint is a Rego policy that checks claims extracted from AI output.

Project context:
{context}

Generate a rigor.yaml file with constraints tailored to THIS specific project. Include:

1. BELIEFS: Facts about this project that an AI must not get wrong
   - What APIs/functions exist and what they actually do
   - What dependencies are used and their REAL capabilities (not hallucinated ones)
   - What the architecture looks like
   - Domain-specific knowledge that's easy to hallucinate

2. JUSTIFICATIONS: Evidence requirements
   - What claims need test evidence
   - What claims need documentation references

3. DEFEATERS: Contradiction detectors
   - What claims would contradict each other
   - What WIP/prototype markers should block production claims

4. RELATIONS: How constraints connect
   - Which justifications support which beliefs
   - Which defeaters attack which beliefs

For each constraint, write valid Rego using OPA v1 syntax:
- Use `violation contains v if {{ ... }}` (not `violation[msg]`)
- Use `regex.match(pattern, c.text)` for text matching
- Access claims via `some c in input.claims`
- Include constraint_id, violated, claims, reason in violation output

Output ONLY valid rigor.yaml content. No markdown fences. No explanation. Start with `constraints:`.

Make constraints SPECIFIC to this project — not generic templates. Reference actual dependency names, actual API patterns, actual architectural decisions found in the context above."#)
}

/// Extract valid rigor.yaml YAML from an AI response that may contain markdown fences or explanation text.
fn extract_yaml_from_response(response: &str) -> Result<String> {
    let trimmed = response.trim();

    // Try 1: Look for ```yaml ... ``` blocks
    if let Some(start) = trimmed.find("```yaml") {
        let after_fence = &trimmed[start + 7..];
        if let Some(end) = after_fence.find("```") {
            let yaml = after_fence[..end].trim();
            if yaml.contains("constraints:") {
                return Ok(yaml.to_string());
            }
        }
    }

    // Try 2: Look for ```yml ... ``` blocks
    if let Some(start) = trimmed.find("```yml") {
        let after_fence = &trimmed[start + 6..];
        if let Some(end) = after_fence.find("```") {
            let yaml = after_fence[..end].trim();
            if yaml.contains("constraints:") {
                return Ok(yaml.to_string());
            }
        }
    }

    // Try 3: Look for bare ``` ... ``` blocks
    if let Some(start) = trimmed.find("```") {
        let after_fence = &trimmed[start + 3..];
        // Skip the optional language tag on the same line
        let after_newline = after_fence.find('\n').map(|i| &after_fence[i + 1..]).unwrap_or(after_fence);
        if let Some(end) = after_newline.find("```") {
            let yaml = after_newline[..end].trim();
            if yaml.contains("constraints:") {
                return Ok(yaml.to_string());
            }
        }
    }

    // Try 4: Find "constraints:" and take everything from there
    if let Some(start) = trimmed.find("constraints:") {
        let yaml = &trimmed[start..];
        // Trim any trailing ``` or explanation
        let yaml = if let Some(end) = yaml.find("\n```") {
            &yaml[..end]
        } else {
            yaml
        };
        return Ok(yaml.trim().to_string());
    }

    anyhow::bail!("AI response did not contain valid rigor.yaml content. Response preview: {}...", &trimmed.chars().take(200).collect::<String>())
}

/// Run AI-powered init by shelling out to claude CLI.
fn run_ai_init(dir: &Path, project_type: &ProjectType, deps: &[String]) -> Result<String> {
    eprintln!("rigor: gathering project context...");
    let context = gather_project_context(dir, project_type, deps);

    eprintln!("rigor: analyzing project with AI (this may take 30-60 seconds)...");
    let prompt = build_ai_prompt(&context);

    // Try claude CLI — disable all tools so it outputs text directly
    let output = std::process::Command::new("claude")
        .args([
            "--print",
            "--output-format", "text",
            "--disallowed-tools", "Bash,Read,Write,Edit,Grep,Glob,WebFetch,WebSearch",
            "-p", &prompt,
        ])
        .current_dir(dir)
        .output();

    match output {
        Ok(result) if result.status.success() => {
            let response = String::from_utf8_lossy(&result.stdout).to_string();

            // Extract YAML content — find the constraints: block even if wrapped in markdown
            let yaml = extract_yaml_from_response(&response)?;
            Ok(yaml)
        }
        Ok(result) => {
            let stderr = String::from_utf8_lossy(&result.stderr);
            anyhow::bail!("claude CLI failed: {}", stderr)
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            anyhow::bail!(
                "claude CLI not found. Install Claude Code or use 'rigor init' without --ai.\n\
                 Alternatively, set RIGOR_AI_COMMAND to a custom command."
            )
        }
        Err(e) => anyhow::bail!("Failed to run claude CLI: {}", e),
    }
}

pub fn run_init(path: Option<PathBuf>, ai: bool) -> Result<()> {
    let dir = path.unwrap_or_else(|| std::env::current_dir().unwrap());
    let yaml_path = dir.join("rigor.yaml");

    if yaml_path.exists() {
        eprintln!("rigor: rigor.yaml already exists at {}", yaml_path.display());
        // Always install/update the skill even if yaml exists
        if let Err(e) = install_rigor_skill(&dir) {
            eprintln!("rigor: failed to install skill: {}", e);
        }
        // Install action gate hooks
        if let Err(e) = crate::cli::gate::install_hook() {
            eprintln!("rigor init: warning — failed to install gate hook: {}", e);
        }
        return Ok(());
    }

    let project_type = detect_project_type(&dir);
    let deps = detect_dependencies(&dir, &project_type);

    eprintln!("rigor: detected project type: {}", project_type);
    if !deps.is_empty() {
        eprintln!(
            "rigor: detected {} dependencies",
            deps.len()
        );
    }

    let yaml = if ai {
        match run_ai_init(&dir, &project_type, &deps) {
            Ok(ai_yaml) => {
                eprintln!("rigor: AI-generated constraints received");
                // Prepend header
                format!(
                    "# Rigor constraint configuration\n# Project type: {}\n# Generated by: rigor init --ai\n\n{}",
                    project_type, ai_yaml
                )
            }
            Err(e) => {
                eprintln!("rigor: AI init failed: {}", e);
                eprintln!("rigor: falling back to template-based init");
                generate_rigor_yaml(&project_type, &deps)
            }
        }
    } else {
        generate_rigor_yaml(&project_type, &deps)
    };

    // Count constraints
    let belief_count = yaml.matches("epistemic_type: belief").count();
    let justification_count = yaml.matches("epistemic_type: justification").count();
    let defeater_count = yaml.matches("epistemic_type: defeater").count();
    let relation_count = yaml.matches("relation_type:").count();

    std::fs::write(&yaml_path, &yaml)
        .with_context(|| format!("Failed to write {}", yaml_path.display()))?;

    eprintln!("rigor: created {}", yaml_path.display());
    eprintln!(
        "rigor: {} beliefs, {} justifications, {} defeaters, {} relations",
        belief_count, justification_count, defeater_count, relation_count
    );

    // Install /rigor:map Claude Code skill
    install_rigor_skill(&dir)?;

    eprintln!();
    eprintln!("Next steps:");
    eprintln!("  /rigor:map              # open Claude Code, run this to generate constraints from your codebase");
    eprintln!("  rigor validate          # verify the config");
    eprintln!("  rigor show              # see constraints with strengths");
    eprintln!("  rigor graph --web       # explore the constraint graph");

    match crate::cli::gate::install_hook() {
        Ok(_) => {},
        Err(e) => eprintln!("rigor init: warning — failed to install gate hook: {}", e),
    }

    Ok(())
}

/// Install the /rigor:map skill into .claude/commands/ so Claude Code
/// can generate epistemic constraints from the codebase interactively.
fn install_rigor_skill(project_dir: &Path) -> Result<()> {
    let skill_dir = project_dir.join(".claude").join("commands");
    std::fs::create_dir_all(&skill_dir)?;

    let skill_path = skill_dir.join("rigor-map.md");
    std::fs::write(&skill_path, RIGOR_MAP_SKILL)?;
    eprintln!("rigor: installed /rigor:map skill at {}", skill_path.display());
    Ok(())
}

const RIGOR_MAP_SKILL: &str = r#"---
name: rigor-map
description: Analyze the codebase and generate epistemic constraints for rigor.yaml. Run this to create or update the constraint graph that grounds AI outputs against your project's facts.
---

You are generating epistemic constraints for the rigor framework. Rigor enforces factual accuracy of AI outputs by evaluating claims against a constraint graph defined in `rigor.yaml`.

## Your task

1. **Read the existing `rigor.yaml`** if it exists — understand what constraints are already defined
2. **Analyze the codebase** — read key files to understand the project:
   - README, main entry point, config files, package manifest (Cargo.toml / package.json / etc.)
   - Core types, exported APIs, key behaviors
   - Architecture: pipeline steps, data flow, module structure
   - Configuration: thresholds, defaults, modes, env vars
3. **Identify facts that must never be misrepresented** — these become constraints:
   - API surface: what functions/types exist and what they do
   - Architecture: how many steps in a pipeline, what depends on what
   - Behavior: error handling mode (fail-open vs fail-closed), default values
   - Dependencies: what libraries are used and what they support
   - Performance: latency budgets, scaling limits
4. **Generate constraints** in rigor.yaml format
5. **Present the constraints to the user** for review before writing

## Constraint YAML format

```yaml
constraints:
  beliefs:
    - id: example-constraint
      name: Human Readable Name
      description: What must be true about this project
      rego: |
        violation contains v if {
          some c in input.claims
          contains(c.text, "wrong thing")
          v := {"constraint_id": "example-constraint", "violated": true, "claims": [c.id], "reason": "Why this is wrong"}
        }
      message: "Human-readable violation message"
      tags: [domain, category]
  justifications:
    - id: evidence-constraint
      name: Evidence Required
      description: Supporting evidence requirement
      rego: |
        violation contains v if {
          some c in input.claims
          # ... rego logic
        }
      message: "Violation message"
      tags: [evidence]
  defeaters:
    - id: defeating-constraint
      name: Defeater Name
      description: What would invalidate a belief
      rego: |
        violation contains v if {
          some c in input.claims
          # ... rego logic
        }
      message: "Violation message"
      tags: [defeater]

relations:
  - from: evidence-constraint
    to: example-constraint
    relation_type: supports
  - from: defeating-constraint
    to: example-constraint
    relation_type: attacks
```

## Rules

- Use **Rego v1 syntax**: `violation contains v if` NOT deprecated `violation[msg]`
- Import helpers: Rego snippets are automatically wrapped in a module with `import data.rigor.helpers`
- Each constraint should catch a **specific factual error**, not be overly broad
- Use `contains(c.text, "keyword")` for text matching — case-sensitive by default, use `lower(c.text)` for case-insensitive
- The constraint_id in the violation object MUST match the constraint's `id` field
- Claims have fields: `id`, `text`, `confidence`, `claim_type`
- Aim for 8-15 constraints per project — enough to cover key facts, not so many that context is bloated

## Epistemic types

- **belief**: Core factual claim about the project (strength 0.8). "regorus is a subset of OPA"
- **justification**: Supporting evidence that strengthens beliefs (strength 0.9). "test evidence required for functional claims"
- **defeater**: Contradicting evidence that weakens beliefs (strength 0.7). "prototype markers defeat production-ready claims"

## Process

1. Read the codebase thoroughly
2. Draft constraints
3. Show them to the user with explanations
4. Ask for approval/changes
5. Write to rigor.yaml (merge with existing if present)
6. Run `rigor validate` to verify the config
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_detect_rust_project() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\nname = \"test\"").unwrap();
        assert_eq!(detect_project_type(tmp.path()), ProjectType::Rust);
    }

    #[test]
    fn test_detect_python_project() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("pyproject.toml"), "[project]").unwrap();
        assert_eq!(detect_project_type(tmp.path()), ProjectType::Python);
    }

    #[test]
    fn test_detect_typescript_project() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("tsconfig.json"), "{}").unwrap();
        assert_eq!(detect_project_type(tmp.path()), ProjectType::TypeScript);
    }

    #[test]
    fn test_detect_go_project() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("go.mod"), "module test").unwrap();
        assert_eq!(detect_project_type(tmp.path()), ProjectType::Go);
    }

    #[test]
    fn test_detect_unknown() {
        let tmp = TempDir::new().unwrap();
        assert_eq!(detect_project_type(tmp.path()), ProjectType::Unknown);
    }

    #[test]
    fn test_generate_yaml_has_rust_language_defaults() {
        let yaml = generate_rigor_yaml(&ProjectType::Rust, &[]);
        assert!(yaml.contains("rust-no-gc"));
        assert!(yaml.contains("rust-no-null"));
        assert!(yaml.contains("rust-no-exceptions"));
        assert!(yaml.contains("rust-no-inheritance"));
        assert!(yaml.contains("rust-ownership"));
    }

    #[test]
    fn test_generate_yaml_has_registered_dep_constraints() {
        let yaml = generate_rigor_yaml(&ProjectType::Rust, &["regorus".to_string(), "axum".to_string(), "tokio".to_string()]);
        assert!(yaml.contains("regorus-capabilities"));
        assert!(yaml.contains("axum-is-tower-based"));
        assert!(yaml.contains("tokio-is-async-runtime"));
    }

    #[test]
    fn test_generate_yaml_skips_unknown_deps() {
        let yaml = generate_rigor_yaml(&ProjectType::Rust, &["serde".to_string(), "some-unknown-crate".to_string()]);
        // serde has no registered constraints, should not appear
        assert!(!yaml.contains("serde-capabilities"));
    }

    #[test]
    fn test_init_creates_file() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("Cargo.toml"), "[package]\nname = \"test\"\n[dependencies]\ntokio = \"1\"").unwrap();
        run_init(Some(tmp.path().to_path_buf()), false).unwrap();
        assert!(tmp.path().join("rigor.yaml").exists());
        let content = std::fs::read_to_string(tmp.path().join("rigor.yaml")).unwrap();
        assert!(content.contains("Rust"));
        assert!(content.contains("tokio"));
    }

    #[test]
    fn test_init_skips_existing() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("rigor.yaml"), "existing").unwrap();
        run_init(Some(tmp.path().to_path_buf()), false).unwrap();
        // Should NOT overwrite
        let content = std::fs::read_to_string(tmp.path().join("rigor.yaml")).unwrap();
        assert_eq!(content, "existing");
    }
}
