//! Built-in constraint defaults — language-level and dependency-level truths
//! that ship with the rigor binary.
//!
//! Three tiers:
//!   1. Language defaults — truths about Rust/TS/Python/Go itself
//!   2. Dependency defaults — truths about specific crates/packages
//!   3. Project constraints — generated by /rigor:map (not here)

pub mod deps;
pub mod go;
pub mod rust;
